### PR TITLE
Alaa2

### PR DESCRIPTION
**Pull request by alaashhadat**

### CODE REVIEW

**Comment by ArcoMul** [comment]
Hi @alaashhadat 

Nice work, I'm seeing some smart solutions. Personally I didn't even know that `array.flat()` existed, I'm also learning something here 😄 

Did you run the tests with `npm run test-week3` though? As you might have noticed not all tests pass currently. **Step2-3** has two errors. Could you fix those? Or let me know where you are stuck?

Also your description of what happens in **step2-7** is not correct. Make sure to Google "javascript pass by value pass by reference" as metioned in the MAKEME.md file and give it another try :-)

**Comment by wouterkleijn** [comment]
@ArcoMul @alaashhadat Is this homework finished or does it still need work?

**Comment by alaashhadat** [comment]
Hello 
i already fixed what @ArcoMul  asked me to do

**Comment by wouterkleijn** [comment]
> Hello
> i already fixed what @ArcoMul asked me to do

You are absolutely right, Alaa. My apologies and well done :)

**Pull request closed without merging**
