### PR TITLE
run tests for week2 automatically

### PR DESCRIPTION
**Pull request by wilgert**
so we don't need to checkout the Pull Requests locally to verify if the code works, but instead have travis do that work.

### CODE REVIEW

**Comment by wilgert** [comment]
Interesting catch22 here...

**Comment by wilgert** [comment]
Yes I figured that. Maybe we need to create separate repositories per week, so we can really use unit tests and travis like they're supposed to.

**Comment by remarcmij** [comment]
I should mention that @NoerGitKat and @wouterkleijn have pushed back a bit on using unit tests at this stage as they report seeing students becoming confused by the extra tooling. Let's see how this class is doing.

**Comment by NoerGitKat** [comment]
This is what we have observed so far. I must say, however, that increasingly I have come to understand that students are confused by the homework in general (irrespective of the unit tests). I hope rewriting the curriculum will clear this up more. I'll keep you all up to date about that!

**Pull request closed without merging**
