### PR TITLE
Week2 fixed

### PR DESCRIPTION
**Pull request by heartwhite**
a clear branch??

### CODE REVIEW

**Comment by wilgert** [comment]
Looks like I had a wrong assumption: that the `master` branch in your fork is the same as the `master` branch here. But you have merged your branch from week1 into `master` that's why it shows up like this.

**Comment by heartwhite** [comment]
than. if its ok I can delete my forked repo from my page. I fork again and clone again. I paste my codes and make a pull request. than my old pull requests disappear maybe but is it problem??

**Comment by wilgert** [comment]
Then your week1 homework pull request will be gone as well. I would do this:
```
git checkout 513ace2b0f23ee26ac39a8ee5ce0a9d047585048
git checkout -b week2-really-fixed
git cherry-pick 80165067560159af6e6e49b40f32f52358cfffe3
git push -u origin
git branch -d week2-fixed
```

**Comment by heartwhite** [comment]
abdullahs-MacBook-Pro:homework a$ git checkout 513ace2b0f23ee26ac39a8ee5ce0a9d047585048
Note: checking out '513ace2b0f23ee26ac39a8ee5ce0a9d047585048'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 513ace2 Fix broken link

**Pull request closed without merging**
